server:
  port: 8888

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        ## STORAGE SERVICE
        - id: storage-service
          uri: lb://storage-service
          predicates:
            - Path=/api/storages/**
        ## RESOURCE SERVICE
        - id: mp3-resource-service
          uri: lb://resource-service
          predicates:
            - Path=/api/resources/**
        ## SONG SERVICE
        - id: song-service
          uri: lb://song-service
          predicates:
            - Path=/api/songs/**
        ## SERVICE DISCOVERY
        - id: service-discovery
          uri: http://localhost:8761
          predicates:
            - Path=/eureka
          filters:
            - SetPath=/
        ## SERVICE DISCOVERY STYLES
        - id: service-discovery-styles
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE

