server:
  port: 8080

spring:
  rabbitmq:
    exchange: x.mp3-resource-upload
    routingkey: rk.mp3-resource-upload
    queue: q.mp3-resource-upload
  codec:
    max-in-memory-size: 10MB
  application:
    name: resource-processor

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka