server:
  port: 8081

aws:
  region: us-east-1

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
    exchange: x.mp3-resource-upload
    routingkey: rk.mp3-resource-upload
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5001/mp3ResourceDB
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  application:
    name: resource-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka