server:
  port: 8083

spring:
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
    exchange: x.mp3-resource-upload
    routingkey: rk.mp3-resource-upload
    queue: q.mp3-resource-upload
  codec:
    max-in-memory-size: 10MB
  application:
    name: resource-processor

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka