server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  application:
    name: song-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka